name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Run tests
#        run: PYTHONPATH=src pytest --maxfail=1 --disable-warnings -q

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t pdfkatana:ci .

#  security-scan:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build Docker image
#        run: docker build -t pdfkatana:ci .
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@v0.31.0
#        with:
#          image-ref: pdfkatana:ci
#          format: table
#          exit-code: 1
#          ignore-unfixed: true

  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t martinlehnert/pdfkatana:latest -t martinlehnert/pdfkatana:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push martinlehnert/pdfkatana:latest
          docker push martinlehnert/pdfkatana:${{ github.sha }} 